name: Metrics
on:
  schedule:
    - cron: "50 * * * *"
  workflow_dispatch:
  push: {branches: ["master", "main"]}
  pull_request: {}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME_API_KEY }}
          token: ${{ secrets.METRICS_TOKEN }}
          repositories: 1000
          retries: 10
          repositories_affiliations: owner, collaborator
          base: ""
          output_action: commit
          committer_message: "[metrics] update metrics"
          optimize: css, xml, svg
          experimental_features: --optimize-svg
          config_timezone: America/New_York
          plugin_habits: yes
          plugin_habits_charts_type: classic
          plugin_habits_days: 90
          plugin_habits_facts: yes
          plugin_habits_from: 100
          plugin_habits_languages_limit: 10
          plugin_habits_languages_threshold: 5%
          plugin_habits_trim: no
          plugin_wakatime_days: 14
          plugin_wakatime_limit: 14
          plugin_wakatime_repositories_visibility: public
          plugin_wakatime_sections: time, projects, languages,  editors, os
          plugin_wakatime_url: https://wakatime.com
          plugin_wakatime_user: current
          # https://github.com/lowlighter/metrics/blob/master/source/plugins/isocalendar/README.md
          plugin_isocalendar: no
          plugin_isocalendar_duration: half-year

          # https://github.com/lowlighter/metrics/blob/master/source/plugins/calendar/README.md
          plugin_calendar: no
          plugin_calendar_limit: 0

          # https://github.com/lowlighter/metrics/blob/master/source/plugins/achievements/README.md
          plugin_achievements: no
          plugin_achievements_ignored: automater, stargazer, forker, gister # developer, member, explorer, infographile

          # https://github.com/lowlighter/metrics/blob/master/source/plugins/languages/README.md
          plugin_languages: no
          plugin_languages_limit: 5
          plugin_languages_colors: rainbow
          plugin_languages_threshold: 2%
          # Visit https://github.com/lowlighter/metrics#-documentation for full reference
          template: classic
          base_indepth: no
          config_octicon: yes
          plugin_repositories: no
          plugin_repositories_order: featured, pinned, starred, random
